apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      containers:
        - name: promtail
          image: grafana/promtail:2.9.7
          args:
            - -config.file=/etc/promtail/promtail-config.yml
          volumeMounts:
            - name: config
              mountPath: /etc/promtail
            - name: logs
              mountPath: /var/log
            - name: docker
              mountPath: /var/lib/docker/containers
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: promtail-config
        - name: logs
          hostPath:
            path: /var/log
        - name: docker
          hostPath:
            path: /var/lib/docker/containers
---
apiVersion: v1
kind: Service
metadata:
  name: promtail
  namespace: monitoring
spec:
  type: LoadBalancer
  ports:
    - port: 9080
      targetPort: 9080
  selector:
    app: promtail
