const ar = {
  common: {
    loading: 'جار التحميل...',
    error: 'حدث خطأ ما',
    retry: 'إعادة المحاولة',
    cancel: 'إلغاء',
    confirm: 'تأكيد',
    save: 'حفظ',
    delete: 'حذف',
    edit: 'تعديل',
    back: 'رجوع',
    next: 'التالي',
    skip: 'تخطي',
    done: 'تم',
  },
  auth: {
    login: 'تسجيل الدخول',
    signUp: 'إنشاء حساب',
    logout: 'تسجيل الخروج',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    forgotPassword: 'نسيت كلمة المرور؟',
    noAccount: 'ليس لديك حساب؟',
    hasAccount: 'لديك حساب بالفعل؟',
    appTitle: 'HeartBond',
    appSubtitle: 'عزّز رابطكم كل يوم',
    setupProfileTitle: 'أكمل ملفك الشخصي',
    setupProfileSubtitle: 'أخبرنا ببعض التفاصيل لنخصص تجربتك',
    fullName: 'الاسم',
    fullNamePlaceholder: 'أدخل اسمك',
    dateOfBirth: 'تاريخ الميلاد',
    dateOfBirthPlaceholder: 'YYYY-MM-DD',
    dateOfBirthHint: 'استخدم الصيغة YYYY-MM-DD',
    gender: 'الجنس',
    genderOptional: 'اختياري',
    genderMale: 'ذكر',
    genderFemale: 'أنثى',
    genderNonBinary: 'غير ثنائي',
    genderPreferNotToSay: 'أفضل عدم الإفصاح',
    nickname: 'الاسم المستعار',
    nicknamePlaceholder: 'أدخل اسمك المستعار',
    emailId: 'البريد الإلكتروني',
    emailPlaceholder: 'أدخل بريدك الإلكتروني',
    relationshipStatus: 'الحالة الاجتماعية',
    statusSingle: 'أعزب',
    statusInRelationship: 'في علاقة',
    statusMarried: 'متزوج',
    statusEngaged: 'مخطوب',
    profilePicture: 'الصورة الشخصية',
    addPhoto: 'إضافة صورة',
    changePhoto: 'تغيير الصورة',
    gallery: 'اختر من المعرض',
    camera: 'فتح الكاميرا',
    partnerId: 'معرف الشريك',
    partnerIdPlaceholder: 'أدخل معرف الشريك للمزامنة',
    partnerIdHint: 'إذا كان شريكك يشاركك نفس الحساب',
    partnerName: 'اسم الشريك',
    partnerNamePlaceholder: 'أدخل اسم الشريك',
    anniversaryDate: 'تاريخ الذكرى',
    anniversaryPlaceholder: 'YYYY-MM-DD',
    partnerDob: 'تاريخ ميلاد الشريك',
    partnerDobPlaceholder: 'YYYY-MM-DD',
    partnerCode: 'رمز الشريك',
    partnerCodePlaceholder: 'أدخل رمز الشريك للمزامنة',
    partnerCodeHint: 'إذا كان لدى شريكك التطبيق',
    saveProfile: 'حفظ الملف الشخصي',
    saving: 'جار الحفظ...',
    continue: 'متابعة',
    nameRequired: 'الرجاء إدخال اسمك الكامل',
    nameTooShort: 'يجب أن يتكون الاسم من حرفين على الأقل',
    dateOfBirthRequired: 'الرجاء إدخال تاريخ الميلاد',
    dateOfBirthInvalid: 'الرجاء إدخال تاريخ صالح',
    dateOfBirthFuture: 'لا يمكن أن يكون تاريخ الميلاد في المستقبل',
    profileSaved: 'تم حفظ الملف الشخصي',
    phoneNumber: 'رقم الهاتف',
    phonePlaceholder: 'أدخل رقم الهاتف',
    sendOTP: 'إرسال الرمز',
    termsText: 'بالمتابعة، أنت توافق على شروط الخدمة وسياسة الخصوصية',
    orDivider: 'أو',
    selectCountry: 'اختر الدولة',
    otpVerification: 'التحقق من الرمز',
    enterOTP: 'أدخل الرمز المكون من 6 أرقام المرسل إلى',
    verify: 'تحقق',
    resendOTP: 'إعادة إرسال الرمز',
    resendIn: 'إعادة الإرسال بعد',
    seconds: 'ثانية',
    seedHint: 'استخدم الرمز: 987654',
    verifying: 'جار التحقق...',
    sendingOTP: 'جار إرسال الرمز...',
  },
  tabs: {
    home: 'الرئيسية',
    action: 'الإجراءات',
    memories: 'الذكريات',
    games: 'الألعاب',
    notification: 'الإشعارات',
    profile: 'الملف الشخصي',
  },
  home: {
    welcome: 'مرحباً بعودتك',
    greeting: 'صباح الخير!',
    moodQuestion: 'كيف تشعر؟',
    moodSubtitle: 'اختر مزاجًا وأضف ملاحظة سريعة.',
    moodHelper: 'اختر مزاجًا لتخصيص تسجيلك.',
    noteLabel: 'ملاحظة سريعة',
    notePlaceholder: 'ما الذي يشغل بالك؟',
    submit: 'إرسال',
    saveCheckIn: 'حفظ التسجيل',
    checkInSaved: 'تم حفظ التسجيل',
    selectedMood: 'المزاج المحدد',
    moods: {
      happy: 'سعيد',
      sad: 'حزين',
      angry: 'غاضب',
      neutral: 'محايد',
      excited: 'متحمس',
      stressed: 'متوتر',
    },
    partnerStatus: 'حالة الشريك',
    recentMemories: 'الذكريات الحديثة',
    viewAll: 'عرض الكل',
    relationshipScore: 'درجة العلاقة',
    dayStreak: 'الأيام المتتالية',
    strongConnection: 'تواصل قوي',
    completedToday: 'تم اليوم',
    keepGoing: 'استمر!',
    quickActions: 'إجراءات سريعة',
    addInteraction: 'إضافة تفاعل',
    myAction: 'إجراءاتي',
    ourStory: 'قصتنا',
    myAnalysis: 'تحليلي',
    upcoming: 'القادم',
    noUpcoming: 'لا توجد خطط قادمة — خطط لشيء مميز',
    suggestion: 'اقتراح اليوم',
    markDone: 'تم الإنجاز',
    tryAnother: 'جرب آخر',
    completedForToday: 'تم الإنجاز لليوم!',
    comeBackTomorrow: 'عد غداً لاقتراح جديد',
    thanksForSharing: 'شكراً لمشاركتك',
    wereHereForYou: 'نحن هنا من أجلك!',
    saveNote: 'حفظ الملاحظة',
    noteSaved: 'تم حفظ الملاحظة',
    addNote: 'أضف ملاحظة (اختياري)...',
  },
  action: {
    placeholder: 'الإجراءات قريباً',
  },
  games: {
    placeholder: 'الألعاب قريباً',
  },
  notification: {
    title: 'الإشعارات',
    markAllRead: 'تحديد الكل كمقروء',
    empty: 'لا توجد إشعارات بعد',
  },
  memories: {
    title: 'الذكريات',
    addMemory: 'إضافة ذكرى',
    noMemories: 'لا توجد ذكريات بعد. أضف أول ذكرى لك!',
    step: 'الخطوة {{step}} من 3',
    selectMedia: 'اختر الوسائط',
    mediaSubtitle: 'اختر صورة أو فيديو من هذه اللحظة',
    gallery: 'اختر من المعرض',
    camera: 'فتح الكاميرا',
    selectedPhoto: 'تم اختيار {{count}} صورة',
    selectedPhotos: 'تم اختيار {{count}} صور',
    memoryTitle: 'العنوان',
    titlePlaceholder: 'أعط هذه الذكرى عنواناً',
    titleRequired: 'الرجاء إدخال عنوان',
    description: 'الوصف',
    descriptionPlaceholder: 'صف هذه اللحظة...',
    date: 'التاريخ',
    datePlaceholder: 'YYYY-MM-DD',
    dateFuture: 'لا يمكن أن يكون التاريخ في المستقبل',
    location: 'الموقع',
    locationPlaceholder: 'مثال: باريس، سنترال بارك',
    howYouFelt: 'كيف شعرت؟',
    feelingHappy: 'سعيد',
    feelingRomantic: 'رومانسي',
    feelingFun: 'ممتع',
    feelingEmotional: 'عاطفي',
    privacy: 'الخصوصية',
    private: 'خاص',
    privateDesc: 'أنا فقط يمكنه رؤية هذه الذكرى',
    shared: 'مشارك',
    sharedDesc: 'شريكي يمكنه رؤية هذه الذكرى',
    saving: 'جار الحفظ...',
    saved: 'تم حفظ الذكرى!',
  },
  profile: {
    title: 'الملف الشخصي',
    settings: 'الإعدادات',
    notifications: 'الإشعارات',
    privacy: 'الخصوصية',
    help: 'المساعدة والدعم',
    about: 'حول',
    partnerConnection: 'ربط الشريك',
    invitePartner: 'دعوة الشريك',
    dayStreak: 'يوم متتالي',
    moments: 'لحظات',
    actionsDone: 'إجراءات مكتملة',
    connectWithPartner: 'تواصل مع شريكك',
    togetherSince: 'معاً منذ {{date}} · {{duration}}',
    streak: 'التتابع',
    appVersion: 'Relationship Care v1.0.0',
    account: 'تفاصيل الحساب',
    partnerSubtitle: 'معلومات شريكك',
    notSet: 'غير محدد',
    permissionRequired: 'الإذن مطلوب',
    galleryPermission: 'يلزم الوصول إلى المعرض لاختيار صورة',
    cameraPermission: 'يلزم الوصول إلى الكاميرا لالتقاط صورة',
    relationship: 'العلاقة',
    phone: 'الهاتف',
    email: 'البريد الإلكتروني',
    country: 'البلد',
    dateOfBirth: 'تاريخ الميلاد',
    status: 'الحالة',
    partnerDetails: 'بيانات الشريك',
    aiInsights: 'الرؤى الذكية',
    shareProfile: 'مشاركة الملف',
    shareProfileMessage: 'اطّلع على ملفي الشخصي في HeartBond!',
    editProfile: 'تعديل الملف الشخصي',
    edit: 'تعديل الملف الشخصي',
    editProfileHint: 'تحديث بياناتك الشخصية',
    partner: 'الشريك',
    score: 'الدرجة',
    daysTogether: 'أيام',
    totalActions: 'إجمالي الإجراءات',
    latestMood: 'آخر مزاج',
    relationshipSnapshot: 'نظرة على العلاقة',
    anniversary: 'ذكرى الزواج',
    gallery: 'اختر من المعرض',
    camera: 'فتح الكاميرا',
  },
  questions: {
    title: 'أخبرنا عن علاقتك',
    subtitle: 'هذه الأسئلة تساعدنا في تخصيص تجربتك',
    q1: 'منذ متى وأنت مع شريكك؟',
    less6: 'أقل من 6 أشهر',
    '6to1': '6 أشهر - سنة',
    '1to3': '1 - 3 سنوات',
    '3to5': '3 - 5 سنوات',
    more5: 'أكثر من 5 سنوات',
    q2: 'ما هي لغة الحب الأساسية لديك؟',
    affirmation: 'كلمات التأكيد',
    qualityTime: 'وقت الجودة',
    gifts: 'تلقي الهدايا',
    actsOfService: 'أعمال الخدمة',
    physicalTouch: 'اللمس الجسدي',
    q3: 'كم مرة لديك مواعيد غرامية؟',
    weekly: 'أسبوعياً',
    biweekly: 'كل أسبوعين',
    monthly: 'شهرياً',
    rarely: 'نادراً',
    never: 'أبداً',
    q4: 'ما هي أكبر قوة في علاقتك؟',
    communication: 'التواصل',
    trust: 'الثقة',
    sharedInterests: 'الاهتمامات المشتركة',
    mutualRespect: 'الاحترام المتبادل',
    emotionalSupport: 'الدعم العاطفي',
    q5: 'ما هو نشاطك المفضل معاً؟',
    travelling: 'السفر',
    cooking: 'الطهي وتناول الطعام معاً',
    movies: 'مشاهدة الأفلام والمسلسلات',
    outdoor: 'الأنشطة الخارجية',
    talking: 'مجرد التحدث',
  },
  settings: {
    title: 'الإعدادات',
    theme: 'المظهر',
    language: 'اللغة',
    notifications: 'الإشعارات',
    light: 'فاتح',
    dark: 'داكن',
    system: 'النظام',
  },
};

export default ar;
