const en = {
  common: {
    loading: 'Loading...',
    error: 'Something went wrong',
    retry: 'Retry',
    cancel: 'Cancel',
    confirm: 'Confirm',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    back: 'Back',
    next: 'Next',
    skip: 'Skip',
    done: 'Done',
  },
  auth: {
    login: 'Log In',
    signUp: 'Sign Up',
    logout: 'Log Out',
    email: 'Email',
    password: 'Password',
    forgotPassword: 'Forgot Password?',
    noAccount: "Don't have an account?",
    hasAccount: 'Already have an account?',
    appTitle: 'HeartBond',
    appSubtitle: 'Grow closer, every single day',
    setupProfileTitle: 'Complete your profile',
    setupProfileSubtitle: 'Tell us a few details so we can personalize your experience',
    fullName: 'Name',
    fullNamePlaceholder: 'Enter your name',
    dateOfBirth: 'Date of Birth',
    dateOfBirthPlaceholder: 'YYYY-MM-DD',
    dateOfBirthHint: 'Use the format YYYY-MM-DD',
    gender: 'Gender',
    genderOptional: 'Optional',
    genderMale: 'Male',
    genderFemale: 'Female',
    genderNonBinary: 'Non-binary',
    genderPreferNotToSay: 'Prefer not to say',
    nickname: 'Nickname',
    nicknamePlaceholder: 'Enter your nickname',
    emailId: 'Email ID',
    emailPlaceholder: 'Enter your email',
    relationshipStatus: 'Relationship Status',
    statusSingle: 'Single',
    statusInRelationship: 'In a Relationship',
    statusMarried: 'Married',
    statusEngaged: 'Engaged',
    profilePicture: 'Profile Picture',
    addPhoto: 'Add Photo',
    changePhoto: 'Change Photo',
    gallery: 'Choose from Gallery',
    camera: 'Open Camera',
    partnerId: 'Partner ID',
    partnerIdPlaceholder: 'Enter partner ID to sync',
    partnerIdHint: 'If your partner shares the same account',
    partnerName: 'Partner Name',
    partnerNamePlaceholder: 'Enter partner name',
    anniversaryDate: 'Anniversary Date',
    anniversaryPlaceholder: 'YYYY-MM-DD',
    partnerDob: "Partner's Date of Birth",
    partnerDobPlaceholder: 'YYYY-MM-DD',
    partnerCode: 'Partner Code',
    partnerCodePlaceholder: 'Enter partner code to sync',
    partnerCodeHint: 'If your partner has the app',
    saveProfile: 'Save Profile',
    saving: 'Saving...',
    continue: 'Continue',
    nameRequired: 'Please enter your full name',
    nameTooShort: 'Name must be at least 2 characters',
    dateOfBirthRequired: 'Please enter your date of birth',
    dateOfBirthInvalid: 'Please enter a valid date',
    dateOfBirthFuture: 'Date of birth cannot be in the future',
    profileSaved: 'Profile saved',
    phoneNumber: 'Phone Number',
    phonePlaceholder: 'Enter phone number',
    sendOTP: 'Send OTP',
    termsText: 'By continuing, you agree to our Terms of Service and Privacy Policy',
    orDivider: 'or',
    selectCountry: 'Select Country',
    otpVerification: 'Verify OTP',
    enterOTP: 'Enter the 6-digit code sent to',
    verify: 'Verify',
    resendOTP: 'Resend OTP',
    resendIn: 'Resend in',
    seconds: 's',
    seedHint: 'Use code: 987654',
    verifying: 'Verifying...',
    sendingOTP: 'Sending OTP...',
  },
  tabs: {
    home: 'Home',
    action: 'Action',
    memories: 'Memories',
    games: 'Games',
    notification: 'Notification',
    profile: 'Profile',
  },
  home: {
    welcome: 'Welcome back',
    greeting: 'Good Morning!',
    moodQuestion: 'How are you feeling?',
    moodSubtitle: 'Pick a mood and add a quick note.',
    moodHelper: 'Select a mood to personalise your check-in.',
    noteLabel: 'Quick note',
    notePlaceholder: 'What is on your mind?',
    submit: 'Submit',
    saveCheckIn: 'Save check-in',
    submitted: 'Submitted',
    selectedMood: 'Selected mood',
    moods: {
      happy: 'Happy',
      sad: 'Sad',
      angry: 'Angry',
      neutral: 'Neutral',
      excited: 'Excited',
      stressed: 'Stressed',
    },
    partnerStatus: 'Partner Status',
    recentMemories: 'Recent Memories',
    viewAll: 'View All',
    relationshipScore: 'Relationship Score',
    dayStreak: 'Day Streak',
    strongConnection: 'Strong connection',
    completedToday: 'Completed today',
    keepGoing: 'Keep it going!',
    quickActions: 'Quick Actions',
    addInteraction: 'Add Interaction',
    myAction: 'My Action',
    ourStory: 'Our Story',
    myAnalysis: 'My Analysis',
    upcoming: 'Upcoming',
    noUpcoming: 'No upcoming plans — plan something special',
    suggestion: "Today's Suggestion",
    markDone: 'Mark as Done',
    tryAnother: 'Try Another',
    completedForToday: 'Completed for today!',
    comeBackTomorrow: 'Come back tomorrow for a new suggestion',
    thanksForSharing: 'Thanks for sharing',
    wereHereForYou: "We're here for you!",
    saveNote: 'Save Note',
    noteSaved: 'Note saved',
    addNote: 'Add a note (optional)...',
  },
  action: {
    title: "Today's Actions",
    subtitle: 'Small acts, big impact.',
    completedToday: 'Completed Today',
    ideasForYou: 'Ideas for You',
    refresh: 'Refresh Ideas',
    addCustom: 'Add Custom Action',
    markDone: 'Mark as Done',
    customActionTitle: 'What did you do?',
    customActionPlaceholder: 'e.g., Bought flowers, Cooked dinner...',
    customActionSubmit: 'Add Action',
    cancel: 'Cancel',
  },
  games: {
    placeholder: 'Games coming soon',
  },
  notification: {
    title: 'Notifications',
    markAllRead: 'Mark all read',
    empty: 'No notifications yet',
  },
  memories: {
    title: 'Memories',
    addMemory: 'Add Memory',
    noMemories: 'No memories yet. Add your first memory!',
    step: 'Step {{step}} of 3',
    selectMedia: 'Select Media',
    mediaRequired: 'Please select a media',
    mediaSubtitle: 'Choose a photo or video from this moment',
    gallery: 'Choose from Gallery',
    camera: 'Open Camera',
    selectedPhoto: 'Selected {{count}} photo',
    selectedPhotos: 'Selected {{count}} photos',
    memoryTitle: 'Title',
    titlePlaceholder: 'Give this memory a title',
    titleRequired: 'Please enter a title',
    description: 'Description',
    descriptionPlaceholder: 'Describe this moment...',
    date: 'Date',
    datePlaceholder: 'YYYY-MM-DD',
    dateFuture: 'Date cannot be in the future',
    location: 'Location',
    locationPlaceholder: 'e.g. Paris, Central Park',
    howYouFelt: 'How did you feel?',
    feelingHappy: 'Happy',
    feelingRomantic: 'Romantic',
    feelingFun: 'Fun',
    feelingEmotional: 'Emotional',
    privacy: 'Privacy',
    private: 'Private',
    privateDesc: 'Only I can see this memory',
    shared: 'Shared',
    sharedDesc: 'My partner can see this memory',
    saving: 'Saving...',
    saved: 'Memory saved!',
    deleteConfirm: 'Are you sure you want to delete this memory?'
  },
  profile: {
    title: 'Profile',
    settings: 'Settings',
    notifications: 'Notifications',
    privacy: 'Privacy',
    help: 'Help & Support',
    about: 'About',
    partnerConnection: 'Partner Connection',
    invitePartner: 'Invite Partner',
    dayStreak: 'day streak',
    moments: 'moments',
    actionsDone: 'actions done',
    connectWithPartner: 'Connect with your partner',
    togetherSince: 'Together since {{date}} · {{duration}}',
    streak: 'Streak',
    appVersion: 'Relationship Care v1.0.0',
    account: 'Account',
    partnerSubtitle: "Your partner's information",
    notSet: 'Not set',
    permissionRequired: 'Permission required',
    galleryPermission: 'Gallery access is needed to choose a photo',
    cameraPermission: 'Camera access is needed to take a photo',
    relationship: 'Relationship',
    phone: 'Phone',
    email: 'Email',
    country: 'Country',
    dateOfBirth: 'Date of Birth',
    status: 'Status',
    partnerDetails: 'Partner',
    aiInsights: 'AI Insights',
    shareProfileMessage: 'Check out my HeartBond profile!',
    editProfile: 'Edit Profile',
    edit: 'Edit Profile',
    editProfileHint: 'Update your personal details',
    partner: 'Partner',
    score: 'Score',
    daysTogether: 'Days',
    totalActions: 'Total Actions',
    latestMood: 'Latest Mood',
    relationshipSnapshot: 'Relationship Snapshot',
    anniversary: 'Anniversary',
    gallery: 'Choose from Gallery',
    camera: 'Open Camera',
  },
  questions: {
    title: 'Tell us about your relationship',
    subtitle: 'These questions help us personalize your experience',
    q1: 'How long have you been with your partner?',
    less6: 'Less than 6 months',
    '6to1': '6 months - 1 year',
    '1to3': '1 - 3 years',
    '3to5': '3 - 5 years',
    more5: 'More than 5 years',
    q2: 'What is your primary love language?',
    affirmation: 'Words of Affirmation',
    qualityTime: 'Quality Time',
    gifts: 'Receiving Gifts',
    actsOfService: 'Acts of Service',
    physicalTouch: 'Physical Touch',
    q3: 'How often do you have date nights?',
    weekly: 'Weekly',
    biweekly: 'Every 2 weeks',
    monthly: 'Monthly',
    rarely: 'Rarely',
    never: 'Never',
    q4: 'What is the biggest strength in your relationship?',
    communication: 'Communication',
    trust: 'Trust',
    sharedInterests: 'Shared Interests',
    mutualRespect: 'Mutual Respect',
    emotionalSupport: 'Emotional Support',
    q5: 'What is your favorite activity to do together?',
    travelling: 'Travelling',
    cooking: 'Cooking & eating together',
    movies: 'Watching movies & shows',
    outdoor: 'Outdoor activities',
    talking: 'Just talking',
  },
  settings: {
    title: 'Settings',
    theme: 'Theme',
    language: 'Language',
    notifications: 'Notifications',
    light: 'Light',
    dark: 'Dark',
    system: 'System',
    syncPartner: 'Sync Partner',
    syncPartnerTitle: 'Sync your partner',
    enterPartnerCode: 'Enter partner code',
    unsync: 'Unsync',
    sync: 'Sync',
  },
  onboarding: {
    title: 'Stronger Bonds for Busy Lives',
    subtitle: 'Designed for corporate professionals and busy couples to maintain meaningful relationships.',
    card1Title: 'Smart Suggestions',
    card1Desc: 'Get quick, personalized activities that fit easily into your occupied workday.',
    card2Title: 'Cherished Memories',
    card2Desc: 'Store and celebrate your special milestones in a secure, private space.',
    card3Title: 'Relationship Health',
    card3Desc: 'Understand your bond with thoughtful insights and interactive analytics.',
    getStarted: 'Get Started',
  },
};

export default en;
